### ISSUE TITLE
Network traffic analysis attack is possible as sendFakeInfectedRequest is never referenced in code

### ISSUE THREAD

**Issue by secursive** [DP-3T/dp3t-sdk-android#104]
In order to confuse network traffic analysis attack, it is necessary by design to send dummy request of same size and periodicity as real requests for potential infection. A method has been defined to do that: sendFakeInfectedRequest, but this method is never actually referenced in code.

https://github.com/DP-3T/dp3t-sdk-android/blob/0916c5046bc541b63010dccfec69536a73ff8a73/dp3t-sdk/sdk/src/main/java/org/dpppt/android/sdk/DP3T.java#L197

**Comment by simonroesch** [comment]
This is correct. The including client needs to make sure to call this method, which is done for example in the swiss case here https://github.com/DP-3T/dp3t-app-android-ch/blob/develop/app/src/main/java/ch/admin/bag/dp3t/networking/FakeWorker.java#L86 along with the fake request to the health authority to get an authorization token for a positive test result.
