### ISSUE TITLE
Firebase Analytics

### ISSUE THREAD

**Issue by Xxax** [DP-3T/dp3t-sdk-android#110]
In our app we have found that firebase collects data even if you only use cloud messaging.

This would possibly lead to the fact that users who enter the CovidCode can be registered by Google.

**I have not checked this in the dp3t-sdk-android**. But there is no configuration in the code to switch off Google Analytics
Just wanted to give a hint.

You would have to deactivate it according to these instructions
https://firebase.google.com/docs/analytics/configure-data-collection?platform=android

**Comment by jeffallen** [comment]
Can you point to where Firebase is used? I cannot see any indication it is used.

**Comment by Xxax** [comment]
I thought I read something in the documentation, but I can't find it anymore. 
I can't see anything in the code either. Sorry is my mistake! In that case, this issue can be closed.

**Comment by simonroesch** [comment]
I can confirm, that no firebase framework is included! The latest version of the SDK now includes the Google Nearby API which provides access to the Google Exposure Notification framework.
