### ISSUE TITLE
BLE PDUs not aligned with specs?

### ISSUE THREAD

**Issue by carl-binding** [DP-3T/dp3t-sdk-android#134]
Using Linux based BLE tools (hcidump, hcitool) it is my impression that

    • the app currently broadcasts BLE ADV_SCAN_IND and not, as the Exposure Notification, Bluetooth Specification, Preliminary — Subject to Modification and Extension, April 2020, v1.2 indicates, ADV_NONCONN_IND.

    • the first 3 bytes of the Exposure Notification payload (Flags section) seem to be missing in the received BLE PDUs.

> 04 3E 28 02 01 02 01 **DA CF 52 72 DA 71** 1C 03 03 6F FD 17 16   6F FD 11 33 EC 93 29 3C 71 5A 8C 4A FD 7B F5 62 F6 BC 1E BA   8C 91 BD 

In bold  the 6 bytes BTADDR, followed by one length byte 0x1C == 28, followed by 4 bytes length, type, service UUID (0xFD6F, LSB) and the remainder of the payload.

**Comment by simonroesch** [comment]
I think this is a limitation of the Android system and should be corrected in the ExposureNotification spec. A better place to report this would probably be: https://github.com/google/exposure-notifications-android
