### ISSUE TITLE
Testing in production mode

### ISSUE THREAD

**Issue by jorgejams88** [DP-3T/dp3t-sdk-android#177]
Hi everyone, thanks for your help. This project has been very helpful.

I am having an issue, I'm not sure if it's  EN API related or maybe some tweaking I need to do regarding the parameters. Ever since we stopped using the phones that were whitelisted by Google to have the debug mode for the EN API, the devices that have the app but do not have that toggle, do not send real keys to the server, only fake ones. 

Even after waiting 24 or 48 hours with the app installed, the values obtained from the EN API method getTemporaryExposureKeyHistory() are not considered valid, and the server is only getting fake keys.

What can I do to test? Am I doing anything wrong?

**Comment by simonroesch** [comment]
What exactly do you meen by "are not considered valid"? The SDK always uploads 14 keys to the server, but there is a flag indicating for every key if it is fake or not. Can you share an example upload to your server?

**Comment by jorgejams88** [comment]
Thanks for replying.

I'm sorry, I forgot to post my mistake and close the issue. The thing is that with the current version of the EN API, only phones in debug mode release de key of the current day. So since the onset date I was using to test was incorrect (I was using the date when the user gets the results as reference, not the date when the user got the test), I was not getting any real keys in the array, and therefore they were being sent as fake to the backend.

It was my mistake. Sorry.
