### ISSUE TITLE
provideDiagnosisKeys limit

### ISSUE THREAD

**Issue by albertovecina** [DP-3T/dp3t-sdk-android#181]
If I'm understanding the code, this method -> https://github.com/DP-3T/dp3t-sdk-android/blob/a59b4b563b4cd26637eaa8de85a277c21f8c0d75/dp3t-sdk/sdk/src/main/java/org/dpppt/android/sdk/internal/SyncWorker.java#L308 is limiting the calls to provideDiagnosisKeys to twice per day. What's the point of this limitation? According to the google documentation -> "Calls to this method are limited to 20 per day, except for whitelisted accounts, which are
allowed 1,000 calls per day.", so with the 2 hour Worker that would never fail. Am I wrong? Thanks for your help.

**Comment by simonroesch** [comment]
For every Sync we currently do 10 provideDiagnosisKeys() calls, because we measure exposure for each of the past 10 days individually. This limits us to the 2 possible syncs per day.

**Comment by albertovecina** [comment]
Understood! Thanks!
