### ISSUE TITLE
Error on DP3T.setMatchingParameters method

### ISSUE THREAD

**Issue by albertovecina** [DP-3T/dp3t-sdk-android#183]
The values of attenuationThresHoldLow and attenuationThresHoldMedium should be stetted at the same time. If you set this parameters one by one, you can get an error like this -> "durationAtAttenuationThresHold[0] (60) must be <= than durationAtAttenuationThresHolds[0] (55)", because Its comparing the new attenuationThresHoldLow with the old attenuationThresHoldMedium

https://github.com/DP-3T/dp3t-sdk-android/blob/9451af80f5ee049485b9502b5a1152b0ac663e3a/dp3t-sdk/sdk/src/main/java/org/dpppt/android/sdk/internal/AppConfigManager.java#L151

**Comment by simonroesch** [comment]
Thanks for the feedback, we will include a fix for this and combine the two methods!

**Comment by simonroesch** [comment]
This has been fixed with https://github.com/DP-3T/dp3t-sdk-android/pull/186
