### ISSUE TITLE
[Proposal] Add DI to reduce dependancies between different parts of the SDK

### ISSUE THREAD

**Issue by ButtersHub** [DP-3T/dp3t-sdk-android#19]
We can say roughly that the SDK consists of 5 main logical parts:

1. API, Configuration, Status & Events - [DP3T](https://github.com/DP-3T/dp3t-sdk-android/blob/develop/dp3t-sdk/sdk/src/main/java/org/dpppt/android/sdk/DP3T.java), [AppConfigManager](https://github.com/DP-3T/dp3t-sdk-android/blob/develop/dp3t-sdk/sdk/src/main/java/org/dpppt/android/sdk/internal/AppConfigManager.java)
2. TracingService + BLE functionality - [TracingService](https://github.com/DP-3T/dp3t-sdk-android/blob/develop/dp3t-sdk/sdk/src/main/java/org/dpppt/android/sdk/internal/TracingService.java) & [GATT](https://github.com/DP-3T/dp3t-sdk-android/tree/develop/dp3t-sdk/sdk/src/main/java/org/dpppt/android/sdk/internal/gatt)
3. Encryption of Data - [CryptoModule](https://github.com/DP-3T/dp3t-sdk-android/tree/develop/dp3t-sdk/sdk/src/main/java/org/dpppt/android/sdk/internal/crypto)
4. DB layer - [Database](https://github.com/DP-3T/dp3t-sdk-android/tree/develop/dp3t-sdk/sdk/src/main/java/org/dpppt/android/sdk/internal/database)
5. Sync, Discovery & Report - [SyncWorker](https://github.com/DP-3T/dp3t-sdk-android/blob/develop/dp3t-sdk/sdk/src/main/java/org/dpppt/android/sdk/internal/SyncWorker.java) & [Backend](https://github.com/DP-3T/dp3t-sdk-android/tree/develop/dp3t-sdk/sdk/src/main/java/org/dpppt/android/sdk/internal/backend)

In the current implementation, the parts are very coupled, and that might be challenging for some authorities that would like to use the SDK and replace/extend some parts of the SDK.

For example, if someone wants to use the BLE functionality but replace the Encryption & Sync parts, today, they need to fork the SDK and they will lose the future fixes you will add to the SDK.

**What can be done?**
We can use dependency-injection pattern with interfaces/abstract classes, in such way it will be much easier to test, extend and replace different parts of the code.
To do so we need to define clear interface contracts, at least for the DB, CryptoModule & Sync modules

In addition,  it will be much easier to adjust later the app to the new [Google's Android Contact Tracing API](https://blog.google/documents/55/Android_Contact_Tracing_API.pdf)
 
WDYT?
We started looking in that direction, but we would like to know if it is something that you would like to have as part of your SDK? Or we will have to fork, something we don't want to do

**Comment by simonroesch** [comment]
With the switch to the Google ExposureNotification framework the complexity of this SDK was reduced even further, so we currently don't see the need for DI.
