### ISSUE TITLE
Number of keys sent to backend

### ISSUE THREAD

**Issue by ineiti** [DP-3T/dp3t-sdk-android#194]
Should

https://github.com/DP-3T/dp3t-sdk-android/blob/09455cec95848fbdc75fa6035a8acca9f98e1354/dp3t-sdk/sdk/src/main/java/org/dpppt/android/sdk/internal/backend/models/GaenRequest.java#L40

be changed to always fill up to `30` keys, so that the total numbers of keys is always constant?

I'm not sure what happens with the 1.5 and 1.6 GAEN API version, how many keys will be sent. But if it's more than 14, but less than 30, there might be some information leaked.

The iOS SDK does always send 30 keys:
https://github.com/DP-3T/dp3t-sdk-ios/blob/develop/Sources/DP3TSDK/DP3TParameters.swift#L38

**Comment by simonroesch** [comment]
Yes, it should! Therre is already an open PR for this: https://github.com/DP-3T/dp3t-sdk-android/pull/192

**Comment by ineiti** [comment]
Can you please add a `Closes #194` in the PR #192? That would link the PR and the issue, so once the PR is merged, this issue will automatically be closed.

This allows for a history of issues and where they have been fixed.
