### ISSUE TITLE
It would be useful to set a custom number of syncs per day

### ISSUE THREAD

**Issue by albertovecina** [DP-3T/dp3t-sdk-android#217]
As It's fixed to the max value (6 times/day), it would be useful to have an interface to set a higher time interval. If It helps I have this pending pull request -> https://github.com/DP-3T/dp3t-sdk-android/pull/216

Thanks

**Comment by simonroesch** [comment]
Thank you for this extension. I merged your PR and will be added to the master branch with the next release of the SDK.
