### ISSUE TITLE
change appId in the project init,then  send data error

### ISSUE THREAD

**Issue by nysin** [DP-3T/dp3t-sdk-android#23]
when i run project,i changed the appId using in initing SDK,but, i send the report,it occured eror,
what does the appid used？

**Comment by simonroesch** [comment]
The appId has to be registered in the DiscoveryService: https://github.com/DP-3T/dp3t-sdk-android#initialization-1

If you do not want to add your ApplicationInfo to the Discovery, you can also use the DP3T.init(Context context, ApplicationInfo applicationInfo) method and provide all information directly without using the discovery service at all. Make sure that the backendBaseUrl you provide in ApplicationInfo actual implements the DP3T backend protocol: https://github.com/DP-3T/dp3t-sdk-backend
