### ISSUE TITLE
[PROPOSAL] use Kotlin as programming language

### ISSUE THREAD

**Issue by koehleru** [DP-3T/dp3t-sdk-android#25]
I think it is recommended to implement the library in Kotlin.
It is Google’s preferred language for Android app development.
Over 50% of professional Android developers now use Kotlin as the language to develop their apps.

**Comment by simonroesch** [comment]
We discussed the use of Kotlin at the beginning of the project and chose Java because we want to keep the dependencies of the library to a minimum. But an App including this SDK can easily use Kotlin, but we do not want to force the Kotlin-Dependencies to an App using the SDK and only Java.
