### ISSUE TITLE
Kotlin

### ISSUE THREAD

**Issue by gotev** [DP-3T/dp3t-sdk-android#26]
Given this is a completely new project, which needs maximum reliability, I suggest to migrate the Codebase from Java to Kotlin. It makes a lot of architecture reasoning and testing easier, development faster, not to mention it provides null safety, while being 100% interoperable with existing Java code. It also attracts more developers and the code is similar to Swift on iOS.

If you agree with this, I can help with the migration with a PR.

**Comment by simonroesch** [comment]
Duplicate of https://github.com/DP-3T/dp3t-sdk-android/issues/25
