### ISSUE TITLE
The sample Android app cannot be built with this version of the SDK

### ISSUE THREAD

**Issue by jorgejams88** [DP-3T/dp3t-sdk-android#33]
In order to change the baseURL of the API while compiling the sample Android app, it is convenient to import the source of the sdk instead of importing it via a gradle dependency implementation, because variables (such as the baseURL of the API) cannot be changed if the source is not part of the project.

After building the sdk as an aar file and importing it in the sample Android app, it cannot be built because the sample Android app uses some sdk methods that are not present in this version. 

This can be replicated by builidng default branch when this project is cloned. The master branch is empty. 

To give a clear example, the method getNumberOfHandshakes is not present for the class TracingStatus in this version of the SDK.

I'm sorry if this is not the correct  place to report this.

**Comment by simonroesch** [comment]
the sample app has been updated now.
