### ISSUE TITLE
Discovery endpoint should be configurable

### ISSUE THREAD

**Issue by jorgejams88** [DP-3T/dp3t-sdk-android#42]
In its current state, the discovery URL is hardcoded, it could either be an optional configurable parameter while initializing the SDK or a string value inside an xml resource.

**Comment by simonroesch** [comment]
If you do not want to use the DP3T discovery service, for now you should use the 
DP3T.init(Context, ApplicationInfo) 
method, where you provide all the info that would be fetch from the discovery directly in the ApplicationInfo.
