### ISSUE TITLE
[Privacy] Lower down access position requirements

### ISSUE THREAD

**Issue by julianxhokaxhiu** [DP-3T/dp3t-sdk-android#57]
Hi,

looking at your SDK together with @sroddy we found out this line: https://github.com/DP-3T/dp3t-sdk-android/blob/develop/dp3t-sdk/sdk/src/main/AndroidManifest.xml#L14

As per Android SDK documentation, the permission you ask for grants PRECISE location ( see https://developer.android.com/reference/android/Manifest.permission#ACCESS_FINE_LOCATION ).

I do propose instead the usage of [ACCESS_COARSE_LOCATION](https://developer.android.com/reference/android/Manifest.permission#ACCESS_COARSE_LOCATION) which would still allow you to make usage of the BLE functionalities ( as per https://developer.android.com/about/versions/marshmallow/android-6.0-changes?fbclid=IwAR1n8tdOZ0jiWGc1gbQ_ArRauJwIkL9cdFL8QiYmm75IMUA-8epGeOWwWtc#behavior-hardware-id ) but still enhance the privacy of the end user.

If I got it right, D3-PT is all about this right?

Let me know what you think :)

Cheers,
Julian

**Comment by simonroesch** [comment]
This is not a good idea. As of https://developer.android.com/guide/topics/connectivity/bluetooth#Permissions we need the ACCESS_FINE_LOCATION permission.

**Comment by julianxhokaxhiu** [comment]
Sorry why?

In your very same link this is stated:
```
Note: If your app targets Android 9 (API level 28) or lower, you can declare the ACCESS_COARSE_LOCATION permission instead of the ACCESS_FINE_LOCATION permission.
```

Which makes even more sense. As it targets any device with Android 9 or lower.
