### ISSUE TITLE
DP3T.UPDATE_INTENT_ACTION is not fired on every Status/Config change

### ISSUE THREAD

**Issue by ButtersHub** [DP-3T/dp3t-sdk-android#6]
Currently, form the code DP3T.UPDATE_INTENT_ACTION is fired only if:
1. bluetoothAdapter is disabled
2. there is a handshake

It will be good if it will fire on any Status change, such as:
- numberOfHandshakes
- isAdvertising
- isReceiving;
- wasContactExposed
- lastSyncDate
- reportedAsExposed

Actually, on almost every field that changed in AppConfigManager the event should be fired

**Comment by buenzli-ubique** [comment]
I added more broadcast triggers with https://github.com/DP-3T/dp3t-sdk-android/pull/15 - unless I  missed one, all changes to the status object should be broadcast now.
