### ISSUE TITLE
[Methodology] Regarding proximity tracing

### ISSUE THREAD

**Issue by inecho** [DP-3T/dp3t-sdk-android#62]
So far, I see no distance being computed. How is a close proximity planned to be identified and where will be implemented? Will it be in the [ContactFactory](https://github.com/DP-3T/dp3t-sdk-android/blob/develop/dp3t-sdk/sdk/src/main/java/org/dpppt/android/sdk/internal/crypto/ContactsFactory.java), since an exposure over certain time is marked as a contact (having also those hardcoded rssi values)?

**Comment by Vanuan** [comment]
Android Exposure API uses a "0-255" number to represent a difference between rx and tx signal strength.

Example:

|rssi| tx|distance|
|-----|---|-----------|
|1|255| 255-1 = long|
|255|1| 1-255 = long|
|127|128| 128-127 = close|

**Comment by simonroesch** [comment]
The ExposureNotification framework allows us to get the number of minutes grouped in to three buckets of attenuation values, where we set the threshold for the attenuation values. In our current implementation we use the following formula to compute the number of minutes of contact: lowAttenuation*factorLow+middleAttenuation*factorMiddle and then check if this gives us a value bigger than a certain threshold. Important we check this for each calendar day individually, so if you have exposure just under the threshold every day again you will never get a notification. And we do not try to estimate a distance and then apply a formula/scoring on the distance, but apply the formula directly on the measured attenuation values.
