### ISSUE TITLE
CryptoModule.checkContacts is not conform to the specification and could exposes users to malicious false positives

### ISSUE THREAD

**Issue by luc-devallonne-nagra** [DP-3T/dp3t-sdk-android#64]
This issue is similar to https://github.com/DP-3T/dp3t-sdk-ios/issues/17

The problem lays wih the fact that when a SecretKey is published to the server, it is then public.
Some malicious user could then forge EphIDs for that day, impersonating the infectious person during the rest of the day and potentially create a lot of false positives.

To cover this particular case, the Whitepaper states (page 11):

Each smartphone uses this pair to reconstruct the list of EphIDs of an infected
person for each day t’ and checks if it has observed any of these EphIDs on day t’ in the
past (i.e., before the corresponding key SKt was published)

To comply to the above, I beleive the code in:

https://github.com/DP-3T/dp3t-sdk-android/blob/baa7f293e6f519be9a895636f0c21c9a694e9ba6/dp3t-sdk/sdk/src/main/java/org/dpppt/android/sdk/internal/crypto/CryptoModule.java#L201

should first compute midnight UTC (start of the day) for the bucketTime and then iterate from the onsetDate up to (but not equal) bucketTime midnight UTC.

**Comment by Vanuan** [comment]
I think this is being discussed here:
https://github.com/DP-3T/documents/issues/182

**Comment by luc-devallonne-nagra** [comment]
Actually the implementation is more fine grained than a full day as described in the whitepaper.
Newly released Secret Keys are published on a 2 (configurable?) hours batch window.
This information is carried via the BucketTime when fetched by the device application and there is an explicit check to consider only the contacts seen up to the publication time.

Which should clear the above mentioned threat
