### ISSUE TITLE
Calibration project error

### ISSUE THREAD

**Issue by cpepi001** [DP-3T/dp3t-sdk-android#74]
IDE: IntelliJ IDEA 2020.1

When I open the project I got an error on Run/Debug Configurations: `Error: Module not specified.`

I tried Clean/Build/Rebuild/Sync the project and the error becomes: `Warning: Default Activity not found.` 

I specified the activity to launch MainActivity and the error changes to: `Warning: The activity 'MainActivity' is not declared in AndroidManifest.xml`

Also, I tried Invalidating Cache and restart.

Sometimes works and I can run the app but if not, I have to do a combination of the above to make it run.

**Comment by simonroesch** [comment]
You have to open the project in the calibration-app folder. In the SDK folder there is a plain Android Library project, that you will not be able to install on its own.

**Comment by cpepi001** [comment]
Oh I was opening the dp3t-sdk-android project instead of calibration-app. Now it's fine. I didn't understood exactly what you meant about the Android Library. Do I have to install anything else? The project runs now.

**Comment by simonroesch** [comment]
No you are fine. If you want to build your own application using the SDK, you would only need the SDK project to build the library you include then in your project.

**Comment by kollokollo** [comment]
I have managed to compile and install the app. It shows up as "Calibration" with a green Android-like logo (I think this is the default if no other logo is included). What bothered me was, that this app only installed on a very new phone (HUAWEI) and not on my all-day phone (Samsumg Galayx alpha, Android 5.0). And of course not on my old phone (HUAWEI, Android 4.1) either. Am I an oldie, or wouldn't it be better to make the app also compatible with more older phones?

**Comment by simonroesch** [comment]
At the moment we support Android 6.0 and higher, so yes, you are an oldie ;-)

**Comment by kollokollo** [comment]
Issue #16 says, that Android 5.0 would be possible as well. So I am looking forward to the new versions.
