### ISSUE TITLE
broascast v/s Broadcast key

### ISSUE THREAD

**Issue by dirkx** [DP-3T/dp3t-sdk-android#8]
The various (reference) apps and test vectors use 'Broadcast key' (capital B) - in

https://github.com/DP-3T/dp3t-sdk-android/blob/00c90ed1d1bd07e0cfedc1fd919a5670e99a109f/dp3t-sdk/sdk/src/main/java/org/dpppt/android/sdk/internal/crypto/CryptoModule.java#L44

 	private static final byte[] BROADCAST_KEY = "broadcast key".getBytes(); 

we have something different (lower case b). May be wise to align (took us quite a bit of time to figure out the delta!)

**Comment by simonroesch** [comment]
The reference implementation https://github.com/DP-3T/reference_implementation is now updated to lower case, which is what we want to use everywhere.

**Comment by dirkx** [comment]
@simonroesch Thanks -- may I still argue for https://github.com/DP-3T/documents/issues/155 ? And Cathargo and all that ?
